# TODO: Remove this; just local testing for now. (or make it polished)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castai-cloud-proxy-deployment
  labels:
    app: castai-cloud-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: castai-cloud-proxy
  template:
    metadata:
      labels:
        app: castai-cloud-proxy
    spec:
      serviceAccountName: castai-cloud-proxy
      containers:
        - name: cloud-proxy-container
          image: docker.io/lachezarcast/cloud-proxy@{{IMAGE_DIGEST}}
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "10Mi"
          imagePullPolicy: Always
          command:
            - "castai-cloud-proxy"
          args:
            - "-sanity-checks=false"
            - "-mockcast=true"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CAST_URL
              value: https://api.dev-master.cast.ai
            - name: CAST_GRPC_URL
              value: api-grpc.dev.cast.ai
            - name: CAST_API_KEY
              value: ec82f1670aa140435ab483a3ff2e5f507d67f3a4e276197e6bb9339f1eda9350
            - name: CLUSTER_ID
              value: b8c18bba-ff52-442e-9f44-8dcc9becfc58
            - name: LOG_LEVEL
              value: "5"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: castai-cloud-proxy
  namespace: default