apiVersion: apps/v1
kind: Deployment
metadata:
  name: castai-cloud-proxy-deployment
  labels:
    app: castai-cloud-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: castai-cloud-proxy
  template:
    metadata:
      labels:
        app: castai-cloud-proxy
    spec:
      serviceAccountName: castai-cloud-proxy
      containers:
        - name: cloud-proxy-container
          image: docker.io/lachezarcast/cloud-proxy@{{IMAGE_DIGEST}}
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "10Mi"
          imagePullPolicy: Always
          command:
            - "castai-cloud-proxy"
          args:
            - "-sanity-checks=false"
            - "-mockcast=true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: castai-cloud-proxy
  namespace: default
