// Code generated by MockGen. DO NOT EDIT.
// Source: cloud-proxy/internal/proxy (interfaces: StreamCloudProxyClient)

// Package mock_cloud is a generated GoMock package.
package mock_cloud

import (
	cloudproxyv1alpha "cloud-proxy/proto/v1alpha"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockStreamCloudProxyClient is a mock of StreamCloudProxyClient interface.
type MockStreamCloudProxyClient struct {
	ctrl     *gomock.Controller
	recorder *MockStreamCloudProxyClientMockRecorder
}

// MockStreamCloudProxyClientMockRecorder is the mock recorder for MockStreamCloudProxyClient.
type MockStreamCloudProxyClientMockRecorder struct {
	mock *MockStreamCloudProxyClient
}

// NewMockStreamCloudProxyClient creates a new mock instance.
func NewMockStreamCloudProxyClient(ctrl *gomock.Controller) *MockStreamCloudProxyClient {
	mock := &MockStreamCloudProxyClient{ctrl: ctrl}
	mock.recorder = &MockStreamCloudProxyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamCloudProxyClient) EXPECT() *MockStreamCloudProxyClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockStreamCloudProxyClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockStreamCloudProxyClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockStreamCloudProxyClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockStreamCloudProxyClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockStreamCloudProxyClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockStreamCloudProxyClient)(nil).Context))
}

// Header mocks base method.
func (m *MockStreamCloudProxyClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockStreamCloudProxyClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockStreamCloudProxyClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockStreamCloudProxyClient) Recv() (*cloudproxyv1alpha.StreamCloudProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*cloudproxyv1alpha.StreamCloudProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockStreamCloudProxyClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockStreamCloudProxyClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockStreamCloudProxyClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockStreamCloudProxyClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockStreamCloudProxyClient)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockStreamCloudProxyClient) Send(arg0 *cloudproxyv1alpha.StreamCloudProxyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockStreamCloudProxyClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockStreamCloudProxyClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m *MockStreamCloudProxyClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockStreamCloudProxyClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockStreamCloudProxyClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockStreamCloudProxyClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockStreamCloudProxyClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockStreamCloudProxyClient)(nil).Trailer))
}
