apiVersion: v1
kind: Service
metadata:
  name: {{ include "e2e.fullname" . }}
  labels:
    {{- include "e2e.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "e2e.selectorLabels" . | nindent 4 }}
